### ISSUE TITLE
Bug - Exclamation mark in ROM filenames

### ISSUE THREAD

**Issue by JoseHdz1** [Ryback2501/TendoMode#1]
Can you help me by putting more than 30 games in the same filter the issue does not load, can that error be corrected?

**Comment by Ryback2501** [comment]
Hi. I can load more than 30 games with this theme. Can you check the last_run.log file? I need more information to solve the problem. It is on the root folder of Attract Mode. You will need to run Attract Mode, go to the display and exit attract mode, and then check the last_run.log file.

**Comment by JoseHdz1** [comment]
Attract-Mode v2.6.1 (Windows, SFML 2.5.1 +SWF +7z +Curl) 
avcodec 58.54.100 / avformat 58.29.100 / swscale 5.5.100 / avutil 56.31.100 / swresample 3.5.100

Config: D:\attract\attract.cfg

*** Initializing display: 'Nintendont'
 - Loaded master romlist 'Nes' in 6 ms (50 entries kept, 0 discarded)
 - Constructed 2 filters in 0 ms (100 comparisons)

AN ERROR HAS OCCURED [division by zero]

CALLSTACK
*FUNCTION [constructor()] D:\attract\layouts/TendoMode-0.3/definitions.nut line [296]
*FUNCTION [main()] D:\attract\layouts/TendoMode-0.3/layout.nut line [59]

LOCALS
[i] 30
[len] 50
[margin] 3
[visible_miniatures] 30
[selector_distance] 28
[side] 56
[y] 700
[center_x] 960
[this] INSTANCE
[game_title_text] INSTANCE
[game_title] INSTANCE
[bg] INSTANCE
[current_level] 1
[vargv] ARRAY
[this] TABLE
Script Error in D:\attract\layouts/TendoMode-0.3/layout.nut - division by zero
 - Loaded layout: D:\attract\layouts/TendoMode-0.3/ (layout.nut)

**Comment by Ryback2501** [comment]
I see the error. Do you have roms with an exclamation mark ('!') in their file names? Try to remove them from the filenames and see if the theme works. Ex: Contra[!].nes --> Contra.nes

**Comment by JoseHdz1** [comment]
Thank you very much, your theme is genius, sorry for causing you discomfort

**Comment by Ryback2501** [comment]
There's no discomfort at all. I'm glad you like the theme. I changed the name of the issue.

**Comment by JoseHdz1** [comment]
If I also think that TendoMode is a better name, I also think it would be a great idea to use the menus that oomek created, or at least to generate your own. :3

**Comment by Ryback2501** [comment]
Do you mean [this oomek](https://github.com/oomek)?
